GET http://localhost:9001/label
Accept: application/json

###
POST http://localhost:9001/label
Content-Type: application/json

{
  "labelname": "scala",
  "state": "1",
  "count": 0,
  "recommend": "4"
}

###
