server:
  port: 12000
spring:
  application:
    name: tensquare-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Javfa/tensquare_config.git
  rabbitmq:
    host: 192.168.146.128
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
